= Logging Service

The Logging service configures the logging library used by *Repose*.

Configuration for the logging library is provided by the user.
Configuration allows the user to decide what to log and where to log it.

The *Repose* logging system is currently backed by https://logging.apache.org/log4j/2.x/[Log4j2].

== Configuration
* *Configuration:* log4j2.xml
* *Released:* v1.0

For information on the syntax and semantics of the `log4j2.xml` file, please see https://logging.apache.org/log4j/2.x/manual/configuration.html[the official Log4j2 configuration documentation].

== Additional Information

[WARNING]
====
Log messages that are written before this service has initialized (e.g., Valve logs, core service startup logs) may not appear in the expected, configured log file.
Since this service performs logging configuration, logging that occurs before it has initialized will rely on the Log4j2 default configuration which writes everything to standard streams (i.e., `stdout`, `stderr`).
====
