= OpenTracing Service

The OpenTracing service (http://opentracing.io/) is a service in *Repose* which allows for sending tracing data to a Tracing service.
Tracing data is Tracer specific but nicely abstracted via OpenTracing service.  Currently, the only supported Tracer is Jaeger (http://jaeger.readthedocs.io/en/latest/),
 however other Tracers can be easily integrated in future updates of OpenTracing service.  By default, the service is disabled,
 but can be enabled with including opentracing.cfg.xml configuration.  An origin service can utilize the tracing information internally
 by extracting the span context and injecting it into egress requests; however, that is entirely optional.
 The origin service can simply pass the Tracer-specific header to downstream services and requests will be traced across application boundaries.  Implementation will be covered later in this document.

== Configuration
* *Default Configuration:* opentracing.cfg.xml
* *Released:* vTBD
* link:../schemas/opentracing.xsd[Schema]

=== Service Configuration
The OpenTracing service is activated by adding a `opentracing.cfg.xml` configuration to configuration directory.  By default, simply including the configuration turns the service on; however, the operator can disable the service by setting `enabled="false"` attribute.
This configuration and element are included in the default *Repose* installation.

By default, all requests that are created by the service are reported (sampled).  The operator can optionally supply other sampling configurations:

* `Constant (const)`.  Default is `1`, which means always sample.  Setting this value to `0` will effectively disabled the service
* `Probability (probability)`.  Default is `0.001`, which is equivalent to 1 request sampled per 1000 actual requests.  The range is between `0.0` and `1.0`.
* `Rate limited (rate-limited)`.  Default is `1.0` which is one request per second.

[source,xml]
.opentracing.cfg.xml
----
<?xml version="1.0" encoding="UTF-8"?>

<opentracing xmlns="http://docs.openrepose.org/repose/opentracing/v1.0"
             enabled="true" <!--1-->
             name="my-repose" <!--2-->
             tracer="jaeger" <!--3-->
             collector-endpoint="https://jaeger.collector.example.com"> <!--4-->
    <jaeger-sampling-config sample-type="probabilistic"> <!--5-->
        <jaeger-sampling-probabilistic value="0.9" /> <!--6-->
    </jaeger-sampling-config>
</opentracing>

----
<1> The `opentracing` element's `enabled` attribute must be set to `true` to activate this feature.
<2> The name of the Service/API that this instance of *Repose* is in front of (however, if you are explicitly using OpenTracing in your origin application, you should suffix `-repose` to this configuration as best practice.
<3> Tracer can be set to any supported tracer.  Currently, only `jaeger` is supported
<4> Collector endpoint must be set to the Tracer collector endpoint.
<5> Optional sampling configuration.  Default is `probabilistic`.  Other options include: `const` and `rate-limited`
<6> Probability sampling rate.  Ranges from `0.0` (never) to `1.0` (always)

=== Tracer implementation detail

This section will cover all Tracers that are supported by OpenTracing service.  We will be adding to this list as more tracers as supported.

Current support:

.Table Tracer information
|===
|Tracer Name |Tracer Header    |Extraction examples

|*Jaeger*
|`uber-trace-id`
|https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-apachehttpclient
|===

=== Common configurations ===

* Send tracing data to tracer collector for every request:

[source,xml]
.opentracing.cfg.xml
----
<?xml version="1.0" encoding="UTF-8"?>

<opentracing xmlns="http://docs.openrepose.org/repose/opentracing/v1.0"
             enabled="true" <!--1-->
             name="my-repose" <!--2-->
             tracer="jaeger" <!--3-->
             collector-endpoint="https://jaeger.collector.example.com"> <!--4-->
    <jaeger-sampling-config sample-type="const"> <!--5-->
        <jaeger-sampling-const value="1" /> <!--6-->
    </jaeger-sampling-config>
</opentracing>

----
<1> The `opentracing` element's `enabled` attribute must be set to `true` to activate this feature.
<2> The name of the Service/API that this instance of *Repose* is in front of (however, if you are explicitly using OpenTracing in your origin application, you should suffix `-repose` to this configuration as best practice.
<3> Tracer can be set to any supported tracer.  Currently, only `jaeger` is supported
<4> Collector endpoint must be set to the Tracer collector endpoint.
<5> Optional sampling configuration.  Set to `const`
<6> Set to `1` to always send traces


* Send tracing data to tracer agent for every request:

[source,xml]
.opentracing.cfg.xml
----
<?xml version="1.0" encoding="UTF-8"?>

<opentracing xmlns="http://docs.openrepose.org/repose/opentracing/v1.0"
             enabled="true" <!--1-->
             name="my-repose" <!--2-->
             tracer="jaeger" <!--3-->
             sender-protocol="udp" <!--4-->
             agent-host="jaeger.agent.example.com" <!--5-->
             agent-port="5775"> <!--6-->
    <jaeger-sampling-config sample-type="const"> <!--7-->
        <jaeger-sampling-const value="1" /> <!--8-->
    </jaeger-sampling-config>
</opentracing>

----
<1> The `opentracing` element's `enabled` attribute must be set to `true` to activate this feature.
<2> The name of the Service/API that this instance of *Repose* is in front of (however, if you are explicitly using OpenTracing in your origin application, you should suffix `-repose` to this configuration as best practice.
<3> Tracer can be set to any supported tracer.  Currently, only `jaeger` is supported
<4> Sender protocol is set to `udp`.
<5> Agent host must be set to the Tracer agent host.  Repose will not start if this is misconfigured.
<6> Agent port must be set to the Tracer agent port.  Repose will not start if this is misconfigured.
<7> Optional sampling configuration.  Set to `const`
<8> Set to `1` to always send traces

=== Example usage in origin service
By default, the only thing an origin service needs to do is pass Tracer specific header (`Tracer Header` in `Table 1`) as part of its request to downstream systems.
