= Getting Started
:toclevels: 3

include::../_includes/in-progress.adoc[]

== What is Repose?
Repose is an open-source, RESTful middleware platform that transparently integrates with your existing infrastructure.
Technically, it is a pseudo-transparent reverse proxy.

Repose provides highly scalable, extensible solutions to common API processing tasks including authentication, rate limiting, access control, logging, and more.

Additionally, Repose allows services to use https://en.wikipedia.org/wiki/Enterprise_Integration_Patterns[Enterprise Integration Patterns].

== How Does Repose Work?
Repose takes incoming requests from clients and adjusts them for consumption by services by passing the requests through a series of extensible filters.
These filters provide functionality such as authentication, authorization, rate-limiting, and request modification.
Repose can run as a stand-alone proxy server between the client and the origin service.
The Repose instance can be on the same host as the origin service, but it doesn't have to be.
This deployment method, illustrated in the following graphic, is called <<valve-installation.adoc#,Valve>>.

[ditaa, valve-diagram, png]
....
+------+          +------+    +--------------+
|      +--------->|      +=-->|              |
|Client|          |Repose|    |Origin Service|
|      |<---------+      |<--=+              |
+------+          +------+    +--------------+
....

Repose can also run within a servlet container such as GlassFish or Tomcat using the <<war-installation.adoc#,WAR>> deployment.

[ditaa, war-diagram, png]
....
                  +=-----------------------------+
                  |      Servlet Container       |
+------+          | +------+    +--------------+ |
|      +----------->|      +=-->|              | |
|Client|          | |Repose|    |Origin Service| |
|      |<-----------+      |<--=+              | |
+------+          | +------+    +--------------+ |
                  +------------------------------+
....

You can decide which configuration works best for you, and you can tweak many of your configurations without having to restart Repose – it will pick up configuration changes on the fly, making it easy to configure and test.

Repose can be configured to use a distributed data store service where cached information is exchanged across multiple nodes.
This makes Repose fault tolerant with proven performance.

== What Services Does Repose Provide?
Repose provides a series of customizable filters that you can configure to perform a large number of API tasks.
The full list of filters is on the <<../filters/index.adoc#,Filters>> page.
Following are some of the most common ones:

* <<../filters/translation.adoc#,Translating>> requests and responses so that services receive them in the format that they are expecting.
* <<../filters/rate-limiting.adoc#,Rate limiting>> requests and responses to control network traffic.
* <<../filters/keystone-v2.adoc#,Authenticating>> requests to enhance security.
* <<../filters/api-validator.adoc#,Validating>> that requests conform to XSD and WADL specifications.
* <<../filters/slf4j-http-logging.adoc#,Logging>> to keep inventories of events.
* <<../filters/content-normalization.adoc#,Blacklisting>> to prevent others from spoofing authentication credentials and roles.
* <<../filters/keystone-v2.adoc#Cache,Caching>> to reduce load on authentication services.
* <<role-based-access-control.adoc#,Role-based access control (RBAC)>> to restrict access to authorized users.
* <<../filters/api-validator.adoc#API Coverage,Mapping the state of your API>>.

== Who Can Use Repose?
Anyone can use Repose!
It is an open-source platform for the general public to consume, share, and improve.

== How Can I Use Repose?
To get Repose, log in to your server and run the <<Installation>> commands for your desired environment.
Then, configure your origin service endpoint in the <<../architecture/system-model.adoc#,system model>>, and you are ready to configure <<../filters/index.adoc#,filters>> and <<../services/index.adoc#,services>> that work for you.
We have many sample configurations that you can use to get started.
Or, because Repose is open source, you can <<new-repose-filter.adoc#,build your own>> stacks of reusable software components.

=== Environment Setup
Installation instructions are provided for Debian package managers (e.g., APT) and RPM package managers (e.g., Yum).

Certain deployment methods will handle environment setup automatically.
For more information, see: <<Deployment>>

=== Installation
While Repose can be installed manually, other deployment options are provided to make getting started with Repose easier.
See: <<Deployment>>

Repose can be run as a standalone application using Valve (run either as a Linux service or directly from the JAR) or inside of a servlet container (e.g. Tomcat, GlassFish) using the WAR.

==== Proxy Server (Valve)
This is the most common setup and is detailed on the <<valve-installation.adoc#,Valve Installation>> page.

After installing it this way, consult the <<running-valve.adoc#,Running Valve>> page for details on starting and stopping Repose.

==== Servlet Container WAR
Instructions for installing the WAR are on the <<war-installation.adoc#,WAR Installation>> page.

===== Tomcat Setup

After installing the WAR, there is additional setup to get everything working with Tomcat.
See <<tomcat-setup.adoc#,Tomcat Setup>> for more details.

===== GlassFish Setup

See <<glassfish-setup.adoc#,GlassFish Setup>> for more details.

===== Container Attributes known to affect Repose

See <<http-container-attributes.adoc#,HTTP container attributes>>

=== Deployment
Once you know how you'll want to configure Repose, you may want to automate the deployment using a configuration management tool or reusable container.

==== Vagrant
If you don't already have a Linux environment ready, you can use Vagrant to easily create a new virtual machine running the Linux distribution of your choice.
For more details, see: <<vagrant.adoc#,Vagrant>>

==== Docker
Docker and Repose make a fantastic team together.
For more details, see: <<docker.adoc#,Docker>>

==== Puppet
There is an unsupported starter module in the GitHub repository https://github.com/rackerlabs/puppet-repose[rackerlabs/puppet-repose].

==== Chef
There is an unsupported starter cookbook in the GitHub repository https://github.com/rackerlabs/cookbook-repose[rackerlabs/cookbook-repose].

=== Configuration
If you're ready to dive into configuration, see <<../architecture/configuration.adoc#,Configuration>> for more details.
We also have a series of <<index.adoc#,Recipes>> that will walk you through some of our common use cases.

=== Performance Tuning
Repose has been battle tested in production environments and in our performance testing environments.
See <<performance-best-practices.adoc#,Performance Best Practices>> for more details.

=== Support

==== Recipes
For further information on common configuration scenarios, visit our <<index.adoc#,Recipes>> page.

==== Troubleshooting
For details on common troubleshooting techniques, visit our <<../troubleshooting.adoc#,Troubleshooting>> page.

==== FAQs
For a list of frequently asked questions and answers, visit our <<../faqs.adoc#,FAQs>> page.

== Need More Information About Repose?
<<../contact-us.adoc#,Contact us!>> We would be happy to address any questions, comments, or concerns with anything having to do with Repose!

TIP: If you wonder what we've been working on lately, visit our <<../release-notes.adoc#,release notes>>.
