= Getting Started
:toclevels: 3

To use Repose, start by following the instructions for your desired environment from the <<Installation>> section.
Alternatively, a Repose environment can be created using one of the tools listed in the <<Deployment>> section.

After Repose is installed, start off by customizing your <<../architecture/system-model.adoc#,system model>> configuration for your service.
From there, you are ready to begin configuring any <<../filters/index.adoc#,filters>> and <<../services/index.adoc#,services>> you may need.
See <<Configuration>> for more details!

We have many sample configurations that you can use to get started.
Or, because Repose is open source, you can <<custom-filter-for-repose.adoc#,build your own>> stacks of reusable software components.

== Installation
The most common and preferred way to run Repose is as a standalone application using the Valve installation.
This installation allows Repose to be executed either as a Linux service (e.g., using systemd) or a Java process (by invoking the installed JAR).
An alternative would be to run Repose inside an existing servlet container (e.g., Tomcat, GlassFish) using the WAR installation.

While Repose can be installed manually, there are other deployment options available.
However, these other methods do require a little more System Administration knowledge which is not covered here.
See: <<Deployment>>

=== Proxy Server (Valve)
This is the most common setup and is detailed on the <<valve-installation.adoc#,Valve Installation>> page.

After installing it this way, consult the <<running-valve.adoc#,Running Valve>> page for details on starting and stopping Repose.

=== Servlet Container WAR
Instructions for installing the WAR are on the <<war-installation.adoc#,WAR Installation>> page.

==== Tomcat Setup
After installing the WAR, there is additional setup to get everything working with Tomcat.
See <<tomcat-setup.adoc#,Tomcat Setup>> for more details.

==== GlassFish Setup
See <<glassfish-setup.adoc#,GlassFish Setup>> for more details.

==== Container Attributes known to affect Repose
See <<http-container-attributes.adoc#,HTTP container attributes>>

== Deployment
Once you know how you'll want to configure Repose, you may want to automate the deployment using a configuration management tool or reusable container.

=== Vagrant
If you don't already have a Linux environment ready, you can use Vagrant to easily create a new virtual machine running the Linux distribution of your choice.
For more details, see: <<vagrant.adoc#,Vagrant>>

=== Docker
Docker and Repose make a fantastic team together.
For more details, see: <<docker.adoc#,Docker>>

=== Puppet
There is an unsupported starter module in the GitHub repository https://github.com/rackerlabs/puppet-repose[rackerlabs/puppet-repose].

=== Chef
There is an unsupported starter cookbook in the GitHub repository https://github.com/rackerlabs/cookbook-repose[rackerlabs/cookbook-repose].

== Configuration
If you're ready to dive into configuration, see <<../architecture/configuration.adoc#,Configuration>> for more details.
We also have a series of <<index.adoc#,Recipes>> that will walk you through some of our common use cases.

== Performance Tuning
Repose has been battle tested in production environments and in our performance testing environments.
See <<performance-best-practices.adoc#,Performance Best Practices>> for more details.
