= Recipes

include::../_includes/in-progress.adoc[]

== <<getting-started.adoc#,Getting Started>>
We all need to get started somewhere. If this your first time using *Repose*, then this is the place for you!

== <<custom-filter-for-repose.adoc#,Custom Filter for Repose>>
Learn how to create your own custom filter for Repose!

== <<docker.adoc#,Docker>>
Learn the basics of running and operating Repose in a Docker container!

== <<performance-best-practices.adoc#,Performance Best Practices>>
*IN PROGRESS*

== <<role-based-access-control.adoc#,Role Based Access Control>>
Learn how to implement Role-Based Access Control (RBAC) with Repose!

== <<running-valve.adoc#,Running Valve>>
Details the ways which Repose Valve can be run.

== <<vagrant.adoc#,Vagrant>>
Learn the basics of running and operating Repose in a Vagrant guest VM!

== <<valve-installation.adoc#,Valve Installation>>
Covers the typical Repose setup -- a Valve installation (i.e., standalone application) running as a Linux service.

== <<war-installation.adoc#,WAR Installation>>
Covers setting up Repose inside of a user-provided servlet container.

== <<quick-setup.adoc#,Quick Setup>>
*IN PROGRESS*
If you want to stand up a Repose instance quickly, visit the Quick Setup page.

== <<echo-server.adoc#,Echo Server>>
*IN PROGRESS*
If you're evaluating Repose and want a simple origin service to test against, you can install a local instance of httpbin that will echo back your requests.  See Echo Server Tutorial for more details.

== <<rate-limiting.adoc#,Rate Limiting>>
*IN PROGRESS*
Rate limiting is a common use case for Repose and is easy to test.  See Rate Limiting Tutorial for more details.

== <<basic-authentication.adoc#,Basic Authentication>>
*IN PROGRESS*

== <<distributed-rate-limiting.adoc#,Distributed Rate Limiting>>
*IN PROGRESS*

== <<delegation.adoc#,Delegation>>
*IN PROGRESS*

== <<preventing-xml-bomb.adoc#,Preventing XML bomb attacks>>
*IN PROGRESS*

== <<api-event-flume.adoc#,API Access Event Recording with Flume>>
*IN PROGRESS*

== <<xsd-versioning.adoc#,XSD Versioning Guidelines>>
*IN PROGRESS*
