= Running Valve

Valve allows Repose to run as a standalone application.
Repose currently supports multiple ways of starting and stopping in an effort to provide the most flexibility to operators during the industry wide conversion from System V and Upstart to systemd.
The SystemV and Upstart mechanisms are currently deprecated, and in the future, only support for the systemd way will be provided by the standard installation.

== SystemD
This is the recommended way of starting/stopping Repose.
By default, Repose will log to both the systemd logging system via standard out/err as well as system logs in /var/log/repose.
This behavior can be modified by updating the log4j2.xml in the Repose configuration directory to only log to one or the other depending on the need.

----
# start Repose
sudo systemctl start repose-valve.service

# stop Repose
sudo systemctl stop repose-valve.service

# enable Repose to automatically start during boot
sudo systemctl enable repose-valve.service
----

== *(Deprecated)* Upstart / Service
This is the old way of starting/stopping Repose.

----
# start Repose
sudo service repose-valve start

# stop Repose
sudo service repose-valve stop
----

== *(Deprecated)* System V / Init.d Script
Alternatively, you could start/stop Repose using the init.d script directly.

----
# start Repose
sudo /etc/init.d/repose-valve start

# stop Repose
sudo /etc/init.d/repose-valve stop

----

== Java JAR
As a Java application, Repose can also be run directly from a JAR file.

----
# start Repose
java -jar /usr/share/repose/repose-valve.jar

# stop Repose
# CTRL-C to stop the process, OR if you ran it as a background process:
kill -2 $repose_pid
----
