= Valve Installation
:nexus-releases: https://maven.research.rackspacecloud.com/content/repositories/releases/org/openrepose

include::./_includes/in-progress.adoc[]

Covers the typical *Repose* setup -- a Valve installation (i.e., standalone application) running as a Linux service.

For instructions on starting *Repose* after setup, see: <<running-valve.adoc#,Running Valve>>.

For more information about the packages themselves, see: <<../architecture/packages.adoc#,Packages>>.

== APT Based Linux Distributions
----
# update package lists from the server and install any updates
sudo apt-get update
sudo apt-get upgrade -y

# install potentially missing packages needed to install Repose
sudo apt-get install -y wget

# add openrepose.org repository
wget -O - http://repo.openrepose.org/debian/pubkey.gpg | sudo apt-key add -
sudo sh -c 'echo "deb http://repo.openrepose.org/debian stable main" > /etc/apt/sources.list.d/openrepose.list'
sudo apt-get update

# install Repose
sudo apt-get install -y repose-valve repose-filter-bundle repose-extensions-filter-bundle
----

== Yum Based Linux Distributions
----
# update package lists from the server
sudo yum update -y

# install potentially missing packages needed to install Repose
sudo yum install -y wget

# Add the RPMForge/RepoForge repository to your system using the instructions located at:
#  - http://repoforge.org/use/
sudo yum install -y daemonize

# add openrepose.org repository
sudo wget -O /etc/yum.repos.d/openrepose.repo http://repo.openrepose.org/el/openrepose.repo

# install Repose
sudo yum install -y repose-valve repose-filter-bundle repose-extensions-filter-bundle
----

== Other Operating Systems (e.g., Windows, MacOS)
Native packages are not yet provided for all operating systems.

To install *Repose Valve* on systems that do not support *Repose* packages, see: <<Manual>>

== Manual
[CAUTION]
====
This installation method is not recommended unless necessary.
This method does not verify or modify the environment to accommodate *Repose*.
====

If you want to manually download the application archives, they are available in our Nexus Repository.
The primary archives are:

* {nexus-releases}/valve/[Repose Valve JAR]
* {nexus-releases}/filter-bundle/[Filter Bundle EAR]
* {nexus-releases}/extensions-filter-bundle/[Extensions Filter Bundle EAR]
