#!/bin/bash
#
# Startup script for Repose Valve
#
# chkconfig: 345 85 15     - start or stop process definition within the boot process
# description: Script for starting Repose Valve as a daemon on system startup
# processname: repose-valve
#
#
#
#



# Source function library.
. /etc/rc.d/init.d/functions

CONFIG_DIRECTORY=/etc/repose
NAME=repose-valve
DAEMON_HOME=/usr/share/lib/repose
LOG_PATH=/var/log/repose
PID_FILE=/var/run/$NAME.pid
USER=root
START_ARGS="-c $DAEMON_HOME -p $PID_FILE -u $USER -o $LOG_PATH/stdout.log -e $LOG_PATH/stderr.log -l /var/lock/subsys/$NAME"
JAVA_OPTS=""

JAVA=/usr/bin/java
DAEMON_JAR=${DAEMON_HOME}/valve-launcher.jar
CLEAN=/usr/local/bin/clean-repose-deploy

daemonize=/usr/sbin/daemonize

###########################
# Start daemon
###########################
start()
{
  echo -n "Starting $NAME: "
  $CLEAN $CONFIG_DIRECTORY >> /dev/null 2>&1
  daemon $daemonize $START_ARGS $JAVA $JAVA_OPTS -jar $DAEMON_JAR --config-file $CONFIG_DIRECTORY
  echo
}

###########################
# Stop daemon
###########################
stop()
{
  echo -n "Stopping $NAME: "
  killproc -p $PID_FILE -d 3 $NAME && rm -f /var/lock/subsys/$NAME
  echo
}

# -----------------------------------------------------------------------------
# Script entry point...
# -----------------------------------------------------------------------------
# Source defaults.
. $CONFIG_DIRECTORY/$NAME.conf

if [ ! -d $DAEMON_HOME ]; then
  echo "Unable to find $NAME's directory: $DEAMON_HOME."
  exit 1
fi

if [ ! -d $CONFIG_DIRECTORY ]; then
  echo "Unable to find $CONFIG_DIRECTORY."
  exit 1
fi

if [ ! -d $LOG_PATH ]; then
  echo "Unable to log to $LOG_PATH."
  exit 1
fi

# Switch to the daemon's home directory to do all of this...
cd $DAEMON_HOME

case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  status)
    status -p $PID_FILE $NAME
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
esac
