= Welcome to Repose

include::_includes/in-progress.adoc[]

== How to Navigate These Docs
Here's loosely how these docs are organized.

=== <<recipes/quick-start.adoc#,Quick Start>>
Learn how to stand up *Repose* as quickly as possible.

=== <<recipes/getting-started.adoc#, Getting Started>>
We all need to get started somewhere.
If this your first time using *Repose*, then this is the place for you.

=== <<recipes/index.adoc#, Recipes>>
Mmm, tasty food.
For good food you need a good recipe.
Once you get *Repose* up and running, take a look at these recipes to see how to solve common use cases.

=== <<architecture/index.adoc#, Architecture>>
You've got the basics down, maybe you've jury rigged a couple of recipes together to get some decent functionality, but you want more.
Take a look here to see how *Repose* works its magic and how to turn on some of the more exciting, advanced features.

=== <<filters/index.adoc#, Filters>>
You are a pro at working with *Repose*, you just need to know how to configure that one feature on that one filter.
Well step right up here's where you'll find in depth information on every filter, how to toggle every who's it and what's it, what it's expecting to come in on your request and response, and what it might do to your request and response.

=== <<services/index.adoc#, Services>>
All that stuff for the filters? Yeah, same thing but for all the services *Repose* offers.

=== <<troubleshooting.adoc#,Troubleshooting>>
Oh no, oh no, why is everything on fire?
It's ok, be cool, we can help.
Just take a look at this.

=== <<release-notes.adoc#, Release Notes>>
If you want to know when something specific came into *Repose* you'll find it here.

=== <<style-guide.adoc#, Style Guide>>
You found something missing from the docs?
If there was something missing and you want to help, here's where you would go to figure out how we make a page.

=== <<developer/index.adoc#, Developer Documentation>>
So you have this great idea for a *Repose* feature and you need it like yesterday.
What do you do?
Fork the repository, hack on the code, and submit a Pull Request.
You'll find tribal knowledge of what makes *Repose* tick and how to do things in here.

=== <<faq.adoc#, Frequently Asked Questions (FAQ)>>
Couldn't find the answer to your question elsewhere? Maybe it is hiding on our FAQ page.

=== Search
Know vaguely what you're looking for? You can use the following Google Custom Search Engine to search all of our documentation.

include::_includes/search.adoc[]
