= Welcome to Repose

include::_includes/in-progress.adoc[]

== What is Repose?
Repose is an open-source, RESTful middleware platform that transparently integrates with your existing infrastructure.
Technically, it is a pseudo-transparent reverse proxy.

Repose provides highly scalable, extensible solutions to common API processing tasks including authentication, rate limiting, access control, logging, and more.

Additionally, Repose allows services to use https://en.wikipedia.org/wiki/Enterprise_Integration_Patterns[Enterprise Integration Patterns].

== What Services Does Repose Provide?
Repose provides a series of customizable filters that you can configure to perform a large number of API tasks.
The full list of filters is on the <<../filters/index.adoc#,Filters>> page.
Following are some of the most common ones:

* <<../filters/translation.adoc#,Translating>> requests and responses so that services receive them in the format that they are expecting.
* <<../filters/rate-limiting.adoc#,Rate limiting>> requests and responses to control network traffic.
* <<../filters/keystone-v2.adoc#,Authenticating>> requests to enhance security.
* <<../filters/api-validator.adoc#,Validating>> that requests conform to XSD and WADL specifications.
* <<../filters/slf4j-http-logging.adoc#,Logging>> to keep inventories of events.
* <<../filters/header-normalization.adoc#,Blacklisting>> to prevent others from spoofing authentication credentials and roles.
* <<../filters/keystone-v2.adoc#Cache,Caching>> to reduce load on authentication services.
* <<role-based-access-control.adoc#,Role-based access control (RBAC)>> to restrict access to authorized users.
* <<../filters/api-validator.adoc#,API Coverage>> to map the state of your API.
* <<../architecture/container.adoc#,HTTP Client Authentication>> for federated applications.
* <<../architecture/container.adoc#,SSL/TLS Termination>> and Ciphers/Protocols inclusion/exclusion.

== Who Can Use Repose?
Anyone can use Repose!
It is an open-source platform for the general public to consume, share, and improve.

== How to Navigate These Docs
Here's loosely how these docs are organized.

=== <<recipes/getting-started.adoc#, Getting Started>>
We all need to get started somewhere.
If this your first time using *Repose*, then this is the place for you!

=== <<recipes/index.adoc#, Recipes>>
Mmm, tasty food. For good food you need a good recipe.
Once you get *Repose* up and running take a look at these recipes to see how to solve common use cases.

=== <<architecture/index.adoc#, Architecture>>
You've got the basics down, maybe you've jury rigged a couple of recipes together to get some decent functionality, but you want more.
Take a look here to see how *Repose* works it's magic, and how to turn on some of the more exciting, complicated features.

=== <<filters/index.adoc#, Filters>>
You are a pro at working with *Repose*, you just need to know how to configure that one feature on that one filter.
Well step right up here's where you'll find in depth information on every filter, how to toggle every who's it and what's it, what its expecting to come in on your request and response, and what it might do to your request and response.

=== <<services/index.adoc#, Services>>
All that stuff for the filters? Yeah, same thing but for all the services *Repose* offers.

=== <<troubleshooting.adoc#,Troubleshooting>>
Oh no, oh no, why is everything on fire?
It's ok, be cool, we can help.
Just take a look at this.

=== <<release-notes.adoc#, Release Notes>>
Seriously?
You don't have anything better to do?
Ok, I guess if you really want to know when something specific came into *Repose* you'll find it here.

=== <<style-guide.adoc#, Style Guide>>
You found something missing from the docs?
Impossible, there is no way this magnificent set of documents could ever be incomplete.
But if there were something missing and you wanted to help, here's where you would go to figure out how we try to make a page.

=== <<faq.adoc#, Frequently Asked Questions (FAQ)>>
Couldn't find the answer to your question elsewhere? Maybe it is hiding on our FAQ page.

== Support

=== Recipes
For further information on common configuration scenarios, visit our <<recipes/index.adoc#,Recipes>> page.

=== Troubleshooting
For details on common troubleshooting techniques, visit our <<troubleshooting.adoc#,Troubleshooting>> page.

=== FAQs
For a list of frequently asked questions and answers, visit our <<faq.adoc#,FAQ>> page.

== Need More Information About Repose?
<<contact-us.adoc#,Contact us!>> We would be happy to address any questions, comments, or concerns with anything having to do with Repose!

[TIP]
====
If you wonder what we've been working on lately, visit our <<release-notes.adoc#,release notes>>.
====

=== Search
Know vaguely what you're looking for? You can use the following Google Custom Search Engine to search all of our documentation.

include::_includes/search.adoc[]
