= Welcome to Repose

include::_includes/in-progress.adoc[]
include::_includes/search.adoc[]

== How to Navigate These Docs
Here's loosely how these docs are organized.

=== <<recipes/getting-started.adoc#, Getting Started>>
We all need to get started somewhere, if this your first time using *Repose* this is the place for you.

=== <<recipes/index.adoc#, Recipes>>
Mmm, tasty food. For good food you need a good recipe.
Once you get *Repose* up and running take a look at these recipes to see how to solve common use cases.

=== <<architecture/index.adoc#, Architecture>>
You've got the basics down, maybe you've jury rigged a couple of recipes together to get some decent functionality,
but you want more.
Take a look here to see how *Repose* works it's magic,
and how to turn on some of the more exciting, complicated features.

=== <<filters/index.adoc#, Filters>>
You are a pro at working with *Repose*, you just need to know how to configure that one feature on that one filter.
Well step right up here's where you'll find in depth information on every filter,
how to toggle every who's it and what's it, what its expecting to come in on your request and response,
and what it might do to your request and response.

=== <<services/index.adoc#, Services>>
All that stuff for the filters? Yeah, same thing but for all the services *Repose* offers.

=== <<debugging.adoc#, Debugging>>
Oh no, oh no, why is everything on fire? It's ok, be cool, we can help.
Just take a look at this.

=== <<release-notes.adoc#, Release Notes>>
Seriously? You don't have anything better to do?
Ok, I guess if you really want to know when something specific came into *Repose* you'll find it here.

=== <<style-guide.adoc#, Style Guide>>
You found something missing from the docs?
Impossible, there is no way this magnificent set of documents could ever be incomplete.
But if there were something missing and you wanted to help,
here's where you would go to figure out how we try to make a page.
