= Upgrade to Version 9 from Version 8 Notes

== HTTP Client/Connection Pool Service
. If setting the `chunked-encoding` attribute, it will no longer be set in <<services/http-client.adoc#configuration, HTTP Client Service configuration>> but instead will be set in the <<architecture/system-model.adoc#configuration, System Model configuration>>.
.. Deprecated configuration values have been removed; change `0` to `false` and `1` to `true`.

== For Integrators

=== Core
. The `ServiceClient` utility has been removed.
  The <<services/http-client.adoc#, HTTP Client Service>> clients should be used instead.
. The `HttpComponentFactory` utility has been removed.
  Apache's HTTP client `RequestBuilder` should be used instead.

=== HTTP Client/Connection Pool Service
. The following methods have been removed from the HTTP Client Service API and should no longer be used:
.. `releaseClient`
.. `isAvailable`
.. `getAvailableClients`
.. `shutdown`

=== Akka HTTP Client Service
. This service has been removed.
  Functionality has been migrated to the <<services/http-client.adoc#, HTTP Client Service>>.

=== Request Proxy Service
. The following methods have been removed from the Request Proxy Service API and should no longer be used:
.. `setRewriteHostHeader`
.. `proxyRequest(String, HttpServletRequest, HttpServletResponse, String)`
