= Datastores

*Repose* uses one of the following datastore implementations to store various types of data:

* Local datastore (name: local/default)
* Hazelcast datastore (name: hazelcast)

The local datastore is enabled by default.
The others are enabled by including the appropriate service into your <<../architecture/system-model.adoc#,System Model>> configuration.

== Local Datastore
If no other datastores are configured, then *Repose* will use the local datastore.
The local datastore will store data using the cache on each node.
Data will not be shared among the nodes, so each *Repose* node will have its own copy of the data.
For example, if using rate limiting with the local datastore, then each node will track its own limit information and limit updates will not be shared with other nodes.

== Hazelcast Datastore

As the name implies, this datastore is backed by https://hazelcast.org/[Hazelcast IMDG 3.12.1].
Hazelcast is a highly-configurable, in-memory data grid capable of distributing data across a cluster.

In fact, this datastore is simply a bridge between the datastore API and a https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#map[Hazelcast map].

For details on Hazelcast itself, refer to https://docs.hazelcast.org/docs/3.12/manual/html-single/[Hazelcast documentation].

=== Configuration
* *Default Configuration:* hazelcast-datastore.cfg.xml
* *Released:* vTBD
* link:../schemas/hazelcast-datastore.xsd[Schema]

The Hazelcast Datastore is managed by a service which can be enabled by adding it to the <<../architecture/system-model.adoc#,System Model>> like so:

[source,xml]
.system-model.cfg.xml (partial)
----
<?xml version="1.0" encoding="UTF-8"?>
<system-model xmlns="http://docs.openrepose.org/repose/system-model/v2.0">
  ...
  <services>
    <service name="hazelcast-datastore"/>
  </services>
  ...
</system-model>
----

The Hazelcast Datastore will only be created if the Hazelcast Datastore service is listed in the <<../architecture/system-model.adoc#,System Model>>.

==== Simplified Configuration

This configuration provides a quick and easy way of getting started with the <<Hazelcast Datastore>> without requiring you to understand exactly how Hazelcast works or how its myriad options should be configured.

Technically, this configuration is a subset of the configuration presented by a <<Complete Configuration>>.
If you need finer control of Hazelcast than what this configuration presents, switch to a <<Complete Configuration>>.

===== TCP/IP Cluster

This configuration will define a cluster using IP addresses.

[source,xml]
.hazelcast-datastore.cfg.xml
----
<hazelcast-datastore xmlns="http://docs.openrepose.org/repose/hazelcast-datastore/v1.0">
    <simplified> <!--1-->
        <port>5701</port> <!--2-->
        <join>
            <tcp-ip connection-timeout-seconds="5"> <!--3--> <!--4-->
                <member>127.0.0.1</member> <!--5-->
                <member>123.123.123.123</member>
                <member>255.255.255.255</member>
            </tcp-ip>
        </join>
    </simplified>
</hazelcast-datastore>
----
<1> Specifies that the <<Simplified Configuration>> will be used.
<2> The port which Hazelcast will use to communicate between cluster members.
<3> Specifies that the cluster will be formed by members identified by IP address.
<4> The maximum amount of time (in seconds) Hazelcast will wait while trying to connect to a well known member before giving up. +
    Default: `5`
<5> The IP address of a cluster member.

===== Multicast Cluster

This configuration will define a cluster using multicast.

[source,xml]
.hazelcast-datastore.cfg.xml
----
<hazelcast-datastore xmlns="http://docs.openrepose.org/repose/hazelcast-datastore/v1.0">
    <simplified> <!--1-->
        <port>5701</port> <!--2-->
        <join>
            <multicast> <!--3-->
                <multicast-group>224.2.2.3</multicast-group> <!--4-->
                <multicast-port>54327</multicast-port> <!--5-->
                <multicast-timeout-seconds>2</multicast-timeout-seconds> <!--6-->
                <multicast-time-to-live>32</multicast-time-to-live> <!--7-->
            </multicast>
        </join>
    </simplified>
</hazelcast-datastore>
----
<1> Specifies that the <<Simplified Configuration>> will be used.
<2> The port which Hazelcast will use to communicate between cluster members.
<3> Specifies that the cluster will be formed using multicast.
<4> The multicast group IP address.
    Values can be between `224.0.0.0` and `239.255.255.255`. +
    Default: `224.2.2.3`
<5> The port over which Hazelcast members send and receive discovery messages. +
    Default: `54327`
<6> The period (in seconds) during which a node waits for a multicast response from another node when nodes are starting up. +
    Default: `2`
<7> The time-to-live value for multicast packets sent out to control the scope of multicasts. +
    Defailt: `32`

===== AWS Cluster

This configuration will define a cluster using AWS EC2 discovery.

Not all configuration properties are shown in this example.
For details on how the discovery mechanism works and what other configuration properties exist, see https://github.com/hazelcast/hazelcast-aws[Hazelcast AWS discovery plugin documentation].

[source,xml]
.hazelcast-datastore.cfg.xml
----
<hazelcast-datastore xmlns="http://docs.openrepose.org/repose/hazelcast-datastore/v1.0">
    <simplified> <!--1-->
        <port>5701</port> <!--2-->
        <join>
            <aws connection-timeout-seconds="5"> <!--3--> <!--4-->
                <access-key>my-access-key</access-key> <!--5-->
                <secret-key>my-secret-key</secret-key> <!--6-->
                <region>us-west-1</region> <!--7-->
                <host-header>ec2.amazonaws.com</host-header> <!--8-->
                <security-group-name>hazelcast-sg</security-group-name> <!--9-->
                <tag-key>type</tag-key> <!--10-->
                <tag-value>hz-nodes</tag-value> <!--11-->
            </aws>
        </join>
    </simplified>
</hazelcast-datastore>
----
<1> Specifies that the <<Simplified Configuration>> will be used.
<2> The port which Hazelcast will use to communicate between cluster members.
<3> Specifies that the cluster will be formed using AWS EC2 discovery.
<4> The maximum amount of time (in seconds) Hazelcast will wait while trying to connect to a well known member before giving up. +
    Default: `5`
<5> The access key of the EC2 account being used.
<6> The secret key of the EC2 account being used.
<7> The region where Hazelcast members are running.
    This setting is mutually exclusive with the `host-header` setting. +
    Default: `us-east-1`
<8> The URL that is the entry point for a web service.
    This setting is mutually exclusive with the `region` setting. +
    Default: `ec2.amazonaws.com`
<9> A filter on EC2 Instances using a security group.
<10> A filter on EC2 Instances using a tag key.
<11> A filter on EC2 Instances using a tag value.

===== Kubernetes Cluster

This configuration will define a cluster using Kubernetes discovery.

Not all configuration properties are shown in this example.
For details on how the discovery mechanism works and what other configuration properties exist, see https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes discovery plugin documentation].

[source,xml]
.hazelcast-datastore.cfg.xml
----
<hazelcast-datastore xmlns="http://docs.openrepose.org/repose/hazelcast-datastore/v1.0">
    <simplified> <!--1-->
        <port>5701</port> <!--2-->
        <join>
            <kubernetes> <!--3-->
                <namespace>MY-KUBERNETES-NAMESPACE</namespace> <!--4-->
                <service-name>MY-SERVICE-NAME</service-name> <!--5-->
                <service-label-name>MY-SERVICE-LABEL-NAME</service-label-name> <!--6-->
                <service-label-value>MY-SERVICE-LABEL-VALUE</service-label-value> <!--7-->
            </kubernetes>
        </join>
    </simplified>
</hazelcast-datastore>
----
<1> Specifies that the <<Simplified Configuration>> will be used.
<2> The port which Hazelcast will use to communicate between cluster members.
<3> Specifies that the cluster will be formed using Kubernetes discovery.
<4> The Kubernetes namespace where Hazelcast is running.
    If not specified, the value is taken from the `KUBERNETES_NAMESPACE` or `OPENSHIFT_BUILD_NAMESPACE`  environment variable.
<5> The name of the service to scan for pods.
    If not specified, then all pods in the namespace are scanned.
<6> A filter on pods using a service label name.
<7> A filter on pods using a service label value.

==== Complete Configuration

This configuration will delegate to an external Hazelcast XML configuration file.

The external XML configuration must validate against the https://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd[Hazelcast XML configuration schema].
For details on how to author an external configuration, see https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#composing-declarative-configuration[Hazelcast declarative configuration].

[source,xml]
.hazelcast-datastore.cfg.xml
----
<hazelcast-datastore xmlns="http://docs.openrepose.org/repose/hazelcast-datastore/v1.0">
    <complete href="hazelcast.xml"/> <!--1--> <!--2-->
</hazelcast-datastore>
----
<1> Specifies that the <<Complete Configuration>> will be used.
<2> A direct URL reference to a Hazelcast XML configuration.
    If the URL is not resolvable, this value will be resolved as a file relative to the configuration directory.

=== Security

The best approach to secure a Hazelcast cluster would be to have the cluster communicate exclusively over a secured network.
Unfortunately, Hazelcast IMDG Open Source https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#tlsssl[does not support TLS/SSL for communication between nodes] at this time.

By default, Hazelcast will use ephemeral ports for outbound connections.
If a firewall is in use, it must not prevent Hazelcast from making these connections.
See https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#outbound-ports[Hazelcast's outbound port documentation] on how to configure Hazelcast to work alongside a firewall.

=== Consistency and Availability

Hazelcast supports a number of strategies for ensuring that data remains consistent, however the <<Hazelcast Datastore>> prioritizes availability over consistency.
As a result, consistency cannot be guaranteed by this datastore.
However, replication can be used as an effective way to improve consistency.
While Hazelcast does offer a consistent subsystem, it is not used by this datastore.

For more information, see https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#consistency-and-replication-model[Hazelcast's consistencty and replication model documentation].

=== Metrics

Hazelcast can be configured to report metrics via JMX if desired, but it does so using its own mechanisms, not the <<metrics.adoc#,Metrics Service>>.
For more information on JMX metrics, see https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#jmx-api-per-member[Hazelcast's JMX documentation].
