#!/usr/bin/ruby

require File.join(File.dirname(__FILE__), '/includes/reposebuilder')
require File.dirname(__FILE__)+'/includes/reposefileutils'
include ReposeBuilder 
include ReposeFileUtils
require 'highline/import'

arg = ARGV.shift
case arg
    when "--configure"
        p "configure"
        user = ask "Please input your Cloud Servers Username"
        apikey = ask "Please input your Cloud Servers ApiKey"
        writeCredentials(user,apikey)
        
    when "--create-cluster"
        p "build"
        #check for config file
        if !File.exists?("#{File.expand_path("~/.rcman/rscredentials")}")
            puts "RCMAN does not currently have a Cloud Servers Account to use. Please run './rcman --configure' before creating a cluster"
            exit
        end

        #Build only one cluster at a time
        if File.exists?("/tmp/rsInstances")
            puts "User cannot build more than one cluster at a time."
            answer = ask "Delete current cluster? y/n"
            if answer == 'y'
                puts "Destroying current cluster"
                deleteReposeBox
            else
                puts "Please delete current cluster if you wish to build a new one"
                exit
            end
        end

        newFile "hosts.csv"
        newFile "rsInstances"
        rsInstances = Array.new

        t1 = Thread.new {
            puts "building server 1"
            server1 = buildReposeBox1
            waitForRepose(server1.ip,["8887", "8888", "8889", "8890", "8891", "8892", "8080"])
            logger.info("Repose instance 1 built: #{server1.ip} : #{server1.password} : #{server1.getId}")
            rsInstances.push(server1.getId)
        }
        t2 = Thread.new {
            puts "building server 2..."
            server2 = buildReposeBox2
            waitForRepose(server2.ip,["8080"])
            logger.info("Repose instance 2 built: #{server2.ip} : #{server2.password} : #{server2.getId}")
            rsInstances.push(server2.getId)
        }

        t1.join()
        t2.join()
        writeToFile("/tmp/rsInstances",rsInstances.join(",")) 

    when "--delete-cluster"
        puts "Destroying current cluster"
        deleteReposeBox

    when "-h"
        puts "Valid Arguments for Repose Cluster Manager"
        puts "\t--create-cluster [name of cluster] \t\tBuilds the repose regression environment" 
        puts "\t--delete-cluster\t\t\t\tDeletes the active cluster"
        puts "\t--configure\t\t\t\t\tStarts the configuration for the Repose Cluster Manager"
    else
        p "Please provide valid arguments '-h' for list of arguments"
end

