#!/bin/bash
# chkconfig: 234 20 80
CONFIG_DIRECTORY=/etc/repose

LOG_PATH=/var/powerapi/logs
JAR_DIRECTORY=/usr/share/lib/repose
JAVA=/usr/bin/java
PID_FILE=/var/run/repose-valve
JMX="-Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

if [[ -n "$3" ]]; then
  export SAXON_HOME="$3"
fi

startRepose()
{
    START_ARGS="--start --quiet --oknodo --make-pidfile --pidfile ${PID_FILE}.$3.pid"
#    if [ $1 -eq '8888' ]
#    then
#       start-stop-daemon $START_ARGS --exec $JAVA -- -jar $JAR_DIRECTORY/repose-valve.jar START -k -p $1 -s $2 -c $CONFIG_DIRECTORY/node$3 > $LOG_PATH/node$3/current.log 2>&1 &
#    else
#       start-stop-daemon $START_ARGS --exec $JAVA -- -jar $JAR_DIRECTORY/repose-valve.jar START -p $1 -s $2 -c $CONFIG_DIRECTORY/node$3 > $LOG_PATH/node$3/current.log 2>&1 &
#    fi
    case "$1" in
        9887)
            start-stop-daemon $START_ARGS --exec $JAVA -- -jar $JAR_DIRECTORY/repose-valve.jar START -k -p $1 -s $2 -c $CONFIG_DIRECTORY/valveGroup$3 -cf $4> $LOG_PATH/valveGroup$3/current.log 2>&1 &
            ;;
        9888)
            start-stop-daemon $START_ARGS --exec $JAVA -- $JMX -jar $JAR_DIRECTORY/repose-valve.jar START -p $1 -s $2 -c $CONFIG_DIRECTORY/valveGroup$3 -cf $4> $LOG_PATH/valveGroup$3/current.log 2>&1 &
            ;;
        *)
            start-stop-daemon $START_ARGS --exec $JAVA -- -jar $JAR_DIRECTORY/repose-valve.jar START -p $1 -s $2 -c $CONFIG_DIRECTORY/valveGroup$3 -cf $4> $LOG_PATH/valveGroup$3/current.log 2>&1 &
            ;;
    esac

        
}

stopRepose()
{
    java -jar $JAR_DIRECTORY/repose-valve.jar STOP -p $1 -s $2  -c $CONFIG_DIRECTORY/valveGroup$3 > $LOG_PATH/valveGroup$3/current.log 2>&1 &
}

repose()
{
   for i in {1..3}
      do
	START=`expr $i + 9886`
	STOP=`expr $i + 9817`
	CF=$2
        if [ -z "$CF" ]
        then
           CF="jersey"
        fi
        
	echo "$1 repose on port $START: $CF"
	case $1 in
           start)
	      startRepose $START $STOP $i $CF
	   ;;
           stop)
	      stopRepose  $START $STOP $i
           ;;
        esac
        sleep 1
      done
      sleep 10
      java -jar /root/jolokia-jvm.jar start `cat ${PID_FILE}.2.pid`
}

case $1 in
   start)
      repose $1 $2
     
      ;;

   stop)
     repose $1
      ;;

   restart)
     repose stop
     sleep 4
     repose start
      ;;
esac

exit 0

