#!/bin/bash
# chkconfig: 234 20 80
CONFIG_DIRECTORY=/etc/repose

LOG_PATH=/var/powerapi/logs
JAR_DIRECTORY=/usr/share/lib/repose
JAVA=/usr/bin/java
PID_FILE=/var/run/repose-valve


startRepose()
{
    START_ARGS="--start --quiet --oknodo --make-pidfile --pidfile ${PID_FILE}.$3.pid"
    if [ $1 -eq '8888' ]
    then
       start-stop-daemon $START_ARGS --exec $JAVA -- -jar $JAR_DIRECTORY/repose-valve.jar START -k -p $1 -s $2 -c $CONFIG_DIRECTORY/node$3 > $LOG_PATH/node$3/current.log 2>&1 &
    else
       start-stop-daemon $START_ARGS --exec $JAVA -- -jar $JAR_DIRECTORY/repose-valve.jar START -p $1 -s $2 -c $CONFIG_DIRECTORY/node$3 > $LOG_PATH/node$3/current.log 2>&1 &
    fi
}

stopRepose()
{
    java -jar $JAR_DIRECTORY/repose-valve.jar STOP -p $1 -s $2  -c $CONFIG_DIRECTORY/node$3 > $LOG_PATH/node$3/current.log 2>&1 &
}

repose()
{
   for i in {1..6}
      do
	START=`expr $i + 8886`
	STOP=`expr $i + 8817`
	echo "$1 repose on port $START"
	case $1 in
           start)
	      startRepose $START $STOP $i
	   ;;
           stop)
	      stopRepose  $START $STOP $i
           ;;
        esac
        sleep 1
      done
}

case $1 in
   start)
      repose $1
     
      ;;

   stop)
     repose $1
      ;;

   restart)
     repose stop
     sleep 4
     repose start
      ;;
esac

exit 0

