= Add Header Filter
:toc:

include::../_includes/in-progress.adoc[]

The Add Header filter adds configured headers to a request and/or response.
You can use the filter to add new headers with specific values to a request chain, and it can also replace (i.e. remove any existing headers with the configured name) headers.

== General Filter Information

=== Identification
[%hardbreaks]
*Filter Name:* add-header
*Default Configuration Filename:* add-header.cfg.xml

=== Input
None.

=== Output
Varies based on configuration.

== Configuration

=== Add a New Request Header
This configuration will add a `foo` header to the request with a value of `bar`.
Any existing headers with the same name *will not* be removed, and the quality of the `bar` value will be set to 0.5.

[source,xml]
----
<add-headers xmlns="http://docs.openrepose.org/repose/add-header/v1.0">
    <request>
        <header name="foo"
                overwrite="false"
                quality="0.5">
            bar
        </header>
    </request>
</add-headers>
----

=== Replace a Response Header
This configuration will add a `foo` header to the response with a value of `bar`.
Any existing headers with the same name *will* be removed, and the quality of the `bar` value will be set to 0.5.

[source,xml]
----
<add-headers xmlns="http://docs.openrepose.org/repose/add-header/v1.0">
    <response>
        <header name="foo"
                overwrite="true"
                quality="0.5">
            bar
        </header>
    </response>
</add-headers>
----

=== Modify the Request and Response
This configuration will add a `foo` header to the request with a value of `bar`.
Any existing request headers with the same name *will* be removed, and the quality of the `bar` value will be set to 0.8.

It will also add a `baz` header to the response with a value of `qux`.
Any existing response headers with the same name *will not* be removed, and the quality of the `qux` value will be set to `0.4`.

[source,xml]
----
<add-headers xmlns="http://docs.openrepose.org/repose/add-header/v1.0">
    <request>
        <header name="foo"
                overwrite="true"
                quality="0.8">
            bar
        </header>
    </request>
    <response>
        <header name="baz"
                overwrite="false"
                quality="0.4">
            qux
        </header>
    </response>
</add-headers>
----

=== link:../schemas/add-header.xsd[Schema]
