= Attribute Mapping Policy Validation Filter

include::../_includes/in-progress.adoc[]

This filter will validate attribute mapping policies in requests to the origin service.

The origin service is expected to be an Identity service.
This filter will only take action if the HTTP request method is `PUT`.

== General filter information
* *Name:* attribute-mapping-policy-validation
* *Released:* TBD
* *Bundle:* repose-extensions-filter-bundle

[NOTE]
====
This filter has no configuration.
====

== Prerequisites & Postconditions
=== Required headers
* `Content-Type` - Declares the content type of the policy (e.g., XML or JSON) which will be used during validation.

=== Required preceding filters
None.

=== Request headers created
None.

=== Request body changes
None.

=== Recommended follow-on (succeeding) filters
* <<saml-policy.adoc#,SAML Policy Translation Filter>> - These two filters work well together to provide mechanisms for attribute mapping policy management and application.

=== Response body changes
None.

=== Response headers created
None.

=== Response Status Codes
[cols="2", options="header,autowidth"]
.Status Codes
|===
| Status Code
| Reasons

| `400`
a| * If the policy fails validation.

| `415`
a| * If the `Content-Type` is neither XML nor JSON, and therefore, the policy cannot be validated.
|===

== Additional Information
Since this filter will act on all requests it receives, it is recommended to only add this filter to the filter chain for endpoints that expect an attribute mapping policy body.
The <<../architecture/system-model.adoc#,System Model>> provides a mechanism to construct conditional filter chains based on the request URI.
