#! /bin/sh
#
### BEGIN INIT INFO
# Provides: repose-valve
# Required-Start: $network
# Required-Stop:  $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short Description: Startup script for Repose Valve
# Description: Script for starting Repose Valve as a daemon on system startup
### END INIT INFO

set -e

# Source function library.
. /lib/lsb/init-functions

SHUTDOWN_PORT=8123
CONFIG_DIRECTORY=/etc/repose

JAVA=/usr/bin/java

NAME=repose-valve
DAEMON_HOME=/usr/share/lib/repose
PID_FILE=/var/run/repose-valve.pid
REPOSE_JAR=${DAEMON_HOME}/repose-valve.jar
START_ARGS="--start --quiet --oknodo --make-pidfile --pidfile ${PID_FILE} --background"
CLEAN=/usr/bin/clean-repose-deploy

###########################
# Start daemon
###########################
start_repose()
{
  $CLEAN $CONFIG_DIRECTORY
  start-stop-daemon $START_ARGS --exec $JAVA -- -jar $REPOSE_JAR START -s $SHUTDOWN_PORT -c $CONFIG_DIRECTORY
  log_progress_msg "started"
}

###########################
# Stop daemon
###########################
stop_repose()
{
  start-stop-daemon -p $PID_FILE --stop --retry 2 --exec $JAVA -- -jar $REPOSE_JAR STOP
  log_progress_msg "stopped"
}

# -----------------------------------------------------------------------------
# Script entry point...
# -----------------------------------------------------------------------------
# Switch to the daemon's home directory to do all of this...
cd $DAEMON_HOME

if [ $? -ne 0 ]; then
  echo "Unable to find $NAME's directory."
  exit 1
fi

case "$1" in
  start)
    log_daemon_msg "Starting $NAME"
    start_repose
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping $NAME"
    stop_repose
    log_end_msg 0
    ;;
  restart)
    log_daemon_msg "Restarting $NAME"
    stop_repose
    start_repose
    log_end_msg 0
    ;;
  status)
    status_of_proc -p $PID_FILE $JAVA $NAME && exit 0 || exit $?
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
esac
