= Filters

include::./_includes/in-progress.adoc[]

== <<add-header.adoc#,Add Header Filter>>
Enables users to add new headers and header values to a request and/or response.

== <<api-validator.adoc#,API Validator Filter>>
Validates calls to an API by checking the URI format, enforcing <<../recipes/role-based-access-control.adoc#,Role-Based Access Control (RBAC)>>, ensuring payload schema compliance, and much more.

== <<body-extractor-to-header.adoc#,Body Extractor to Header Filter>>
Extracts a value from the request body and puts it in a request header.

== <<body-patcher.adoc#,Body Patcher Filter>>
Patches request/response bodies using methods native to the content type.

== <<compression.adoc#,Compression Filter>>
*IN PROGRESS*

== <<content-type-stripper.adoc#,Content Type Stripper Filter>>
Removes the `Content-Type` header when no content body is present.

== <<cors.adoc#,CORS Filter>>
Enables users to add support for Cross-Origin Resource Sharing requests.

== <<derp.adoc#,Delegation Response Processor (DeRP) Filter>>
*IN PROGRESS*

== <<destination-router.adoc#,Destination Router Filter>>
*IN PROGRESS*

== <<echo.adoc#,Echo Filter>>
*IN PROGRESS*

== <<exception.adoc#,Exception Filter>>
*IN PROGRESS*

== <<forwarded-proto.adoc#,Forwarded Protocol Filter>>
*IN PROGRESS*

== <<header-normalization.adoc#,Header Normalization filter>>
Conditionally removes headers from a request and/or response.

== <<header-translation.adoc#,Header Translation Filter>>
*IN PROGRESS*

== <<header-user.adoc#,Header User Filter>>
*IN PROGRESS*

== <<herp.adoc#,Highly Efficient Record Processor (HERP) Filter>>
Logs a descriptive event for each API request so that usage can be audited.

== <<ip-user.adoc#,IP User Filter>>
Populates a request header with the client’s IP address.

== <<iri-validator.adoc#,IRI Validator Filter>>
Verifies that the request URI has been properly converted from an IRI.

== <<keystone-v2.adoc#,Keystone v2 Filter>>
Provides a mechanism for authenticating and enriching requests with data from an OpenStack Keystone v2 Identity service.

== <<keystone-v2-authorization.adoc#,Keystone v2 Authorization Filter>>
Authorizes requests based on data about the user making the request.

== <<keystone-v2-basic-auth.adoc#,Keystone v2 Basic Auth Filter>>
*IN PROGRESS*

== <<merge-header.adoc#,Merge Header Filter>>
Merges multiple header lines with the same name into a single header line with multiple comma-separated values.

== <<openstack-identity-v3.adoc#,Openstack Identity v3 Filter>>
*IN PROGRESS*

== <<rate-limiting.adoc#,Rate Limiting Filter>>
Limits the number of requests allowed through *Repose* to the origin service.

== <<regex-rbac.adoc#,RegEx Role Based Access Control (RBAC) Filter>>
Validates calls to an API by checking the requested URI against a series Regular Expressions to enforce <<../recipes/role-based-access-control.adoc#,Role-Based Access Control (RBAC)>>.

== <<scripting.adoc#,Scripting Filter>>
Enables users to write custom filters for *Repose* using a variety of scripting languages.

== <<simple-rbac.adoc#,Simple Role Based Access Control (RBAC) Filter>>
Validates calls to an API by checking the URI format and HTTP method and enforcing <<../recipes/role-based-access-control.adoc#,Role-Based Access Control (RBAC)>> using a simple Domain Specific Language (DSL).

== <<slf4j-http-logging.adoc#,SFL4J HTTP Logging Filter>>
*IN PROGRESS*

== <<split-header.adoc#,Split Header Filter>>
Splits header lines with multiple values into multiple header lines each with a single value.

== <<tenant-culling.adoc#,Tenant Culling Filter>>
Winnows away the tenants that are not relevant to the current request.

== <<translation.adoc#,Translation Filter>>
*IN PROGRESS*

== <<uri-normalization.adoc#,URI Normalization Filter>>
Normalizes the URI of HTTP messages.

== <<uri-stripper.adoc#,URI Stripper Filter>>
*IN PROGRESS*

== <<uri-user.adoc#,URI User Filter>>
*IN PROGRESS*

== <<url-extractor-to-header.adoc#,URL Extractor to Header Filter>>
*IN PROGRESS*

== <<valkyrie-authorization.adoc#,Valkyrie Authorization Filter>>
Authorizes users with permissions from a Valkyrie service, and normalizes request and/or response data given those permissions.

== <<versioning.adoc#,Versioning Filter>>
*IN PROGRESS*
