= Recipes

include::./_includes/in-progress.adoc[]

== <<quick-start.adoc#,Quick Start>>
Learn how to stand up Repose as quickly as possible!

== <<getting-started.adoc#,Getting Started>>
We all need to get started somewhere.
If this your first time using *Repose*, then this is the place for you!

== <<custom-filter-for-repose.adoc#,Custom Filter for Repose>>
Learn how to create your own custom filter for *Repose*!

== <<docker.adoc#,Docker>>
Learn the basics of running and operating *Repose* in a Docker container!

== <<performance-best-practices.adoc#,Performance Best Practices>>
*IN PROGRESS*

== <<role-based-access-control.adoc#,Role Based Access Control>>
Learn how to implement Role-Based Access Control (RBAC) with *Repose*!

== <<running-valve.adoc#,Running Valve>>
Details the ways which *Repose Valve* can be run.

== <<valve-installation.adoc#,Valve Installation>>
Covers the typical *Repose* setup -- a Valve installation (i.e., standalone application) running as a Linux service.

== <<echo-server.adoc#,Echo Server>>
*IN PROGRESS*
If you're evaluating *Repose* and want a simple origin service to test against, you can install a local instance of httpbin that will echo back your requests.

== <<rate-limiting.adoc#,Rate Limiting>>
Rate limiting is a common use case for *Repose* and is easy to test.

== <<multi-tenant.adoc#, Multi Tenant Authorization>>
Handling authorization when resources have multiple tenants.

== <<user-access-events.adoc#, User Access Events>>
*IN PROGRESS*

== <<basic-authentication.adoc#,Basic Authentication>>
*IN PROGRESS*

== <<delegation.adoc#,Delegation>>
*IN PROGRESS*

== <<preventing-xml-bomb.adoc#,Preventing XML bomb attacks>>
Details how to configure *Repose* to help prevent XML bomb attacks.

== <<api-event-flume.adoc#,API Access Event Recording with Flume>>
*IN PROGRESS*

== <<xsd-versioning.adoc#,XSD Versioning Guidelines>>
*IN PROGRESS*

== <<client-authentication.adoc#, SSL/TLS Client Authentication>>
Looking for a little more security talking to *Repose* or maybe from *Repose* to your origin service?
SSL/TLS Client Authentication will allow you to limit traffic to those who present a valid certificate.

== <<functional-test-framework.adoc#, Functional Test Framework>>
Learn how to use the *Repose* functional test framework to create tests for features in *Repose* or its extension components.

== <<header-splitting.adoc#, Header Splitting>>
Details how to make version 9.0+ of *Repose* split headers like earlier versions did.

== <<reason-phrase-normalization.adoc#, Reason Phrase Normalization>>
Details how to normalize the reason phrase on the status line of an HTTP response.

== <<project-karate.adoc#, Problematic Header Handling>>
Details what to do if *Repose* adds headers that might have non-legal values, that you can't otherwise change your configuration to remove (like if they are needed for rate limiting).
