#!/bin/sh

CONFIG_DIR=/etc/repose
SYSTEM_MODEL=$CONFIG_DIR/system-model.cfg.xml

#Detects if the Dist-Datastore filter is present in the system-model.cfg.xml file. If the filter is an active component then this installation will fail.
if $SYSTEM_MODEL | sed '/<!--.*-->/d'| sed '/<!--/,/-->/d' | grep 'filter.*dist-datastore'
then
    echo "Unable to upgrade. system-model.cfg.xml file contains the depricated dist-datastore filter. Please remove and re-run upgrade. For more information on the upgrade:  https://repose.atlassian.net/wiki/display/REPOSE/Release+Notes#ReleaseNotes-Release3.0.0(InProgress:UpdatetoJava1.7,RemoveDDFilter,ModularizeDD,BugFixes)"
    exit 1
else
    exit 0
fi
