= Upgrade to Version 9 from Version 8 Notes

== Core Behavior Changes
. Headers will no longer be split unnecessarily at the boundaries of *Repose*.
  If you were counting on this behavior, or for a list of headers that were being split, see <<../recipes/header-splitting.adoc#, Pre 9.0 Header Splitting>>.
. Headers with an empty value will no longer be automatically removed from requests or responses.
  If you were counting on this behavior, the <<../filters/scripting.adoc#, Scripting Filter>> can be used.
  The scripting filter configuration may look like the following:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<scripting xmlns="http://docs.openrepose.org/repose/scripting/v1.0"
         language="groovy">
  request.headerNames.each { headerName ->
      if (!request.getHeader(headerName)) {
          request.removeHeader(headerName)
      }
  }
  filterChain.doFilter(request, response)
  response.headerNames.each { headerName ->
      if (!response.getHeader(headerName)) {
          response.removeHeader(headerName)
      }
  }
</scripting>
----
. The response status line reason phrase from the origin service will now be forwarded from the origin service.
  If you need *Repose* to normalize the reason phrase, see the <<../recipes/reason-phrase-normalization.adoc#, Reason Phrase Normalization recipe>>.
. Requests can now contain headers with empty values.
  For example, if *Repose* receives a request with the header line `My-Header: `, that header line will now be forwarded to the origin service.
. Some core classes have been renamed.
  If you need to customize the logging behavior for the loggers used by these classes, or if you rely on these classes directly, use the following mapping to update to the new class names:
+
[cols="2", options="header,autowidth"]
|===
| Old Class Name
| New Class Name

| org.openrepose.powerfilter.PowerFilter
| org.openrepose.powerfilter.ReposeFilter

| org.openrepose.powerfilter.PowerFilterChain
| org.openrepose.powerfilter.ReposeFilterChain
|===
. The Response Messaging Service has been removed.
  If you were counting on this behavior, the <<../filters/scripting.adoc#, Scripting Filter>> can be used.
  The scripting filter configuration may look like the following:
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<scripting xmlns="http://docs.openrepose.org/repose/scripting/v1.0"
           language="groovy"><![CDATA[
    import groovy.xml.MarkupBuilder

    //Continue the filter chain
    filterChain.doFilter(request, response)

    //Check to see if we should monkey with the response because we have xml and a 2xx
    if((response.contentType ==~ /.*(xml|XML).*/) && (response.status >= 400) && (response.status < 600)) {

        //Uncommit the response just in case
        response.uncommit()

        //Clear the current response body
        response.resetBuffer()

        //Write the new body
        def xml = new MarkupBuilder(response.getWriter())
        xml.error() {
            status(response.getStatus())
            message(response.getReason())
        }
    }
]]></scripting>
----

== System Model Configuration
. Support for multi-cluster deployments has been removed.
.. The `cluster` element was removed from the <<../architecture/system-model.adoc#, system model>>.
   Remember that a cluster is just a logical grouping of nodes by their functionality, and as such, logical clusters can still be constructed outside of *Repose*.
... *Repose* clusters are no longer supported.
    Instead, an operator will need to define *Repose* behavior per-node.
    In other words, each *Repose* cluster will become a new <<../architecture/system-model.adoc#, system model>> configuration.
    To route a request between *Repose* nodes, see the following bullet.
... Service clusters (via round-robin routing) are no longer supported.
    Instead, an operator may choose to use a router to route traffic between destinations with identical functionality.
    A route could be anything from a physical F5 Load Balancer to a Cloud Load Balancer to an OpenShift service.

== Container Configuration
. The `via` attribute was removed from the <<../architecture/container.adoc#, container configuration>>.
  It has been replaced with the `via-header` element.
  To replicate the previous behavior set the value that was previously in the `via` attribute in the `request-prefix` and `response-prefix` attributes of the new element.
. The `soLingerTime` attribute was removed from the <<../architecture/container.adoc#, container configuration>>.
  The underlying Jetty server no longer respects this value and therefore Repose will no longer expose it.
  To replicate the previous behavior you need to configure it in the operating system.

== Deployment
. Support for installing *Repose* into an existing container has been dropped. For help moving to another deployment see <<../recipes/valve-installation.adoc, Valve Installation>> and <<../recipes/quick-start.adoc, Quick Start with Docker>>.
. The package for valve installation has changed from `repose-valve` to `repose`.
. The <<../filters/scripting.adoc#, Scripting Filter>> has been moved from the `repose-experimental-filter-bundle` to the `repose-filter-bundle`.

== HTTP Client/Connection Pool Service
. If setting the `chunked-encoding` attribute, it will no longer be set in <<../services/http-client.adoc#configuration, HTTP Client Service configuration>> but instead will be set in the <<../architecture/system-model.adoc#configuration, System Model configuration>>.
.. Deprecated configuration values have been removed; change `0` to `false` and `1` to `true`.

== Rackspace Auth User, SAML Policy Translation, and Attribute Mapping Policy Validation Filters
. Consult with identity for where these filters now live.

== Header Normalization Filter
. All matching targets will now be processed, previously only the first target that matched would be evaluated.

== URL Extractor to Header Filter
. All capture groups in the URL regex will now add their captured values to the desired header.
.. If you have configured a URL regex with multiple capture groups but do not desire the values of some of those groups to be added to the header, use the non-capturing group construct (i.e., `(?:X)`).
   See https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#special[the special constructs portion of the Java Pattern documentation] for more information.

== OpenStack Identity v3 Filter
. Removed deprecated caching attributes:
.. `token-cache-timeout` on the `openstack-identity-v3` element; `token` on the `timeouts` element should be used instead.
.. `groups-cache-timeout` on the `openstack-identity-v3` element; `group` on the `timeouts` element should be used instead.
.. `cache-offset` on the `openstack-identity-v3` element; `variance` on the `timeouts` element should be used instead.
. Cache timeouts are now defined in seconds rather than milliseconds.
.. To convert existing timeouts, divide by `1000`.

== Keystone v2 and Keystone v2 Authorization Filters
. The `uri-tenant-quality` attribute was removed; the `validated-tenant-quality` should be used in its place.
. Support for extracting required tenant ID(s) from the URI was removed from the <<../filters/keystone-v2-authorization.adoc#, Keystone v2 Authorization Filter>> and <<../filters/keystone-v2.adoc#, Keystone v2 Filter>> configuration.
  To continue validating tenant ID(s) from the URI, follow these steps:
.. Add the <<../filters/url-extractor-to-header.adoc#, URL Extractor to Header Filter>> to your <<../architecture/filter-chain.adoc#, Filter Chain>> in the <<../architecture/system-model.adoc#, System Model>>.
.. Configure the <<../filters/url-extractor-to-header.adoc#, URL Extractor to Header Filter>> to extract tenant ID(s) to a new header.
... For example, if your <<../filters/keystone-v2-authorization.adoc#, Keystone v2 Authorization Filter>> or <<../filters/keystone-v2.adoc#, Keystone v2 Filter>> was configured with:
+
[source,xml]
----
<uri-extraction-regex>.*/servers/([:\-\w]+)/?.*</uri-extraction-regex>
----
+
Then you would configure the <<../filters/url-extractor-to-header.adoc#, URL Extractor to Header Filter>> with:
+
[source,xml]
----
<extraction url-regex=".*/servers/([:-\w]+)/?.*" header="X-Expected-Tenant"/>
----
.. Replace usage of the `uri-extraction-regex` element with the `header-extraction-name` element in your <<../filters/keystone-v2-authorization.adoc#, Keystone v2 Authorization Filter>> and <<../filters/keystone-v2.adoc#, Keystone v2 Filter>> configuration.
... The value of the `header-extraction-name` element should match the value of the header name configured in the <<../filters/url-extractor-to-header.adoc#, URL Extractor to Header Filter>>.
... Following the previous example, the configured header name would be `X-Expected-Tenant`.
Therefore, the <<../filters/keystone-v2-authorization.adoc#, Keystone v2 Authorization Filter>> or <<../filters/keystone-v2.adoc#, Keystone v2 Filter>> configuration should contain:
+
[source,xml]
----
<header-extraction-name>X-Expected-Tenant</header-extraction-name>
----
+
.. If desired, follow best practice guidelines by adding the configured header name to the <<../filters/header-normalization.adoc#, Header Normalization Filter>> blacklist.
... Following the previous examples, the configured header name would be `X-Expected-Tenant`.
Therefore, the <<../filters/header-normalization.adoc#, Header Normalization Filter>> configuration should contain something like:
+
[source,xml]
----
<blacklist>
    <header id="X-Expected-Tenant"/>
</blacklist>
----

== For Integrators

=== Core
. The `ServiceClient` utility has been removed.
  The <<../services/http-client.adoc#, HTTP Client Service>> clients should be used instead.
. The `HttpComponentFactory` utility has been removed.
  Apache's HTTP client `RequestBuilder` should be used instead.

=== HTTP Client/Connection Pool Service
. The following methods have been removed from the HTTP Client Service API and should no longer be used:
.. `releaseClient`
.. `isAvailable`
.. `getAvailableClients`
.. `shutdown`

=== Akka HTTP Client Service
. This service has been removed.
  Functionality has been migrated to the <<../services/http-client.adoc#, HTTP Client Service>>.

=== Request Proxy Service
. The following methods have been removed from the Request Proxy Service API and should no longer be used:
.. `setRewriteHostHeader`
.. `proxyRequest(String, HttpServletRequest, HttpServletResponse, String)`

=== Reporting Service
. This service has been removed.
  Functionality has been migrated to publish to the the <<../services/metrics.adoc#, Metrics Service>>.
. The `incrementRequestCount` an `getTotalStatusCode` methods can be retireved and manipulated using the following `Meters` and `Timers`:
.. `org.openrepose.core.ResponseCode.Repose.<statusCode>`
.. `org.openrepose.core.ResponseCode.<location>.<statusCodeClass>`
.. `org.openrepose.core.ResponseTime.Repose.<statusCode>`
.. `org.openrepose.core.ResponseTime.<location>.<statusCodeClass>`
