= Upgrade to Version 9 from Version 8 Notes

== Container Configuration
. The `via` attribute was removed from the <<../architecture/container.adoc#, container configuration>>.
  It has been replaced with the `via-header` element.
  To replicate the previous behavior set the value that was previously in the `via` attribute in the `request-prefix` and `response-prefix` attributes of the new element.

== HTTP Client/Connection Pool Service
. If setting the `chunked-encoding` attribute, it will no longer be set in <<services/http-client.adoc#configuration, HTTP Client Service configuration>> but instead will be set in the <<architecture/system-model.adoc#configuration, System Model configuration>>.
.. Deprecated configuration values have been removed; change `0` to `false` and `1` to `true`.

== Rackspace Auth User, SAML Policy Translation, and Attribute Mapping Policy Validation Filters
. Consult with identity for where these filters now live.

== Header Normalization Filter
. All matching targets will now be processed, previously only the first target that matched would be evaluated.

== For Integrators

=== Core
. The `ServiceClient` utility has been removed.
  The <<services/http-client.adoc#, HTTP Client Service>> clients should be used instead.
. The `HttpComponentFactory` utility has been removed.
  Apache's HTTP client `RequestBuilder` should be used instead.

=== HTTP Client/Connection Pool Service
. The following methods have been removed from the HTTP Client Service API and should no longer be used:
.. `releaseClient`
.. `isAvailable`
.. `getAvailableClients`
.. `shutdown`

=== Akka HTTP Client Service
. This service has been removed.
  Functionality has been migrated to the <<services/http-client.adoc#, HTTP Client Service>>.

=== Request Proxy Service
. The following methods have been removed from the Request Proxy Service API and should no longer be used:
.. `setRewriteHostHeader`
.. `proxyRequest(String, HttpServletRequest, HttpServletResponse, String)`
