= Upgrade to Version 9 from Version 8 Notes

== Core Behavior Changes
. Headers will no longer be split unnecessarily at the boundaries of *Repose*.
  If you were counting on this behavior for some reason see <<../recipes/header-splitting.adoc#, Pre 9.0 Header Splitting>>.
. The response status line reason phrase from the origin service will now be forwarded from the origin service.
  If you were expecting *Repose* to normalize the reason phrase, see the <<../recipes/reason-phrase-normalization.adoc#, Reason Phrase Normalization recipe>>.

== Container Configuration
. The `via` attribute was removed from the <<../architecture/container.adoc#, container configuration>>.
  It has been replaced with the `via-header` element.
  To replicate the previous behavior set the value that was previously in the `via` attribute in the `request-prefix` and `response-prefix` attributes of the new element.

== Deployment
. Support for installing *Repose* into an existing container has been dropped. For help moving to another deployment see <<../recipes/valve-installation.adoc, Valve Installation>> and <<../recipes/quick-start.adoc, Quick Start with Docker>>.
. The package for valve installation has changed from `repose-valve` to `repose`.

== HTTP Client/Connection Pool Service
. If setting the `chunked-encoding` attribute, it will no longer be set in <<../services/http-client.adoc#configuration, HTTP Client Service configuration>> but instead will be set in the <<../architecture/system-model.adoc#configuration, System Model configuration>>.
.. Deprecated configuration values have been removed; change `0` to `false` and `1` to `true`.

== Rackspace Auth User, SAML Policy Translation, and Attribute Mapping Policy Validation Filters
. Consult with identity for where these filters now live.

== Header Normalization Filter
. All matching targets will now be processed, previously only the first target that matched would be evaluated.

== URL Extractor to Header Filter
. All capture groups in the URL regex will now add their captured values to the desired header.
.. If you have configured a URL regex with multiple capture groups but do not desire the values of some of those groups to be added to the header, use the non-capturing group construct (i.e., `(?:X)`).
   See https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#special[the special constructs portion of the Java Pattern documentation] for more information.

== OpenStack Identity v3 Filter
. Removed deprecated caching attributes:
.. `token-cache-timeout` on the `openstack-identity-v3` element; `token` on the `timeouts` element should be used instead.
.. `groups-cache-timeout` on the `openstack-identity-v3` element; `group` on the `timeouts` element should be used instead.
.. `cache-offset` on the `openstack-identity-v3` element; `variance` on the `timeouts` element should be used instead.

== For Integrators

=== Core
. The `ServiceClient` utility has been removed.
  The <<../services/http-client.adoc#, HTTP Client Service>> clients should be used instead.
. The `HttpComponentFactory` utility has been removed.
  Apache's HTTP client `RequestBuilder` should be used instead.

=== HTTP Client/Connection Pool Service
. The following methods have been removed from the HTTP Client Service API and should no longer be used:
.. `releaseClient`
.. `isAvailable`
.. `getAvailableClients`
.. `shutdown`

=== Akka HTTP Client Service
. This service has been removed.
  Functionality has been migrated to the <<../services/http-client.adoc#, HTTP Client Service>>.

=== Request Proxy Service
. The following methods have been removed from the Request Proxy Service API and should no longer be used:
.. `setRewriteHostHeader`
.. `proxyRequest(String, HttpServletRequest, HttpServletResponse, String)`

=== Reporting Service
. This service has been removed.
  Functionality has been migrated to publish to the the <<../services/metrics.adoc#, Metrics Service>>.
. The `incrementRequestCount` an `getTotalStatusCode` methods can be retireved and manipulated using the following `Meters` and `Timers`:
.. `org.openrepose.core.ResponseCode.Repose.<statusCode>`
.. `org.openrepose.core.ResponseCode.<location>.<statusCodeClass>`
.. `org.openrepose.core.ResponseTime.Repose.<statusCode>`
.. `org.openrepose.core.ResponseTime.<location>.<statusCodeClass>`
