#!/bin/sh
# Repose Lint startup script

REPOSE_LINT="/usr/share/repose/repose-lint.jar"

# Locate a JDK installation directory which will be used to run the IDE.
# Try (in order): JDK_HOME, JAVA_HOME, "java" in PATH.
if [ -n "$JDK_HOME" -a -x "$JDK_HOME/bin/java" ]; then
  JAVA_BIN="$JDK_HOME/bin/java"
elif [ -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
  JAVA_BIN="$JAVA_HOME/bin/java"
else
  JAVA_BIN=$(which java)
fi

# Note: If JAVA_BIN is set to a link, the link may be executable even though the underlying file is not.
if [ ! -x "$JAVA_BIN" ]; then
  echo "ERROR: Cannot start Repose Lint"
  echo "No Java binary found. Please validate that either the JDK_HOME or JAVA_HOME environment variable points to a valid Java installation, or that an executable Java binary is on the path."
  exit 1
fi

exec "$JAVA_BIN" "-jar" "$REPOSE_LINT" "$@"
