#!/bin/sh

CONFIG_DIR=/etc/repose
SYSTEM_MODEL=$CONFIG_DIR/system-model.cfg.xml

# IF this is not a new install,
# THEN make sure we are compatible with the current configuration;
# Create the Repose user and group if they don't exist.
if [ -f $SYSTEM_MODEL ]
then
    # Detects if the Dist-Datastore filter is present in the system-model.cfg.xml file.
    # If the filter is an active component then this installation will fail.
    if cat $SYSTEM_MODEL | sed '/<!--.*-->/d'| sed '/<!--/,/-->/d' | grep 'filter.*dist-datastore'
    then
        echo "Unable to upgrade. The existing system-model.cfg.xml file contains the deprecated dist-datastore filter."
        echo "Please remove and re-run upgrade. For more information on the upgrade go to:"
        echo " - https://repose.atlassian.net/wiki/display/REPOSE/Release+Notes#ReleaseNotes-Release3.0.0(InProgress:UpdatetoJava1.7,RemoveDDFilter,ModularizeDD,BugFixes)"
        exit 1
    fi
fi
getent group  repose >> /dev/null 2>&1 || groupadd -r repose
getent passwd repose >> /dev/null 2>&1 || \
   useradd -r -g repose -s /sbin/nologin -d /usr/share/repose -c "Repose" repose
exit 0
